### ISSUE TITLE
How will Octopress/Jekyll handle the "captions"?

### ISSUE THREAD

**Issue by krrrcks** [octopress/multilingual#1]
Hi, I have only little to zero knowledge of the implementation details of Octopress/Jekyll. Therefore maybe my ideas/questions are already solved. In that case please just close the issue.

The idea of multilangual sites sounds great. 

What I was looking for (and perhaps it is solved in the new Jekyll/Octopress release) is a method for the "captions". 

I would suggest to define "captions" for all the text, menu entries, links (e.g. for "Recent posts", "Older", "Blog Archives" in case of Octopress). Somewhere the English texts are defined for these captions. If I want to switch to a new (not yet existing) language, I add an entry `lang=de` and somewhere have to define all the captions (e.g. in YAML) and perhaps a time/date format: 

```
lang: de
captions: 
  - blog_archives: "Archiv"
  - older: "Ältere Einträge"
...
```

That perhaps would it make easier for people to have a Non-English blog because there would be a central place for defining those captions. 

I hope I made clear what I was thinking about. And perhaps it is already solved in the 3.0 release.

**Comment by drallgood** [comment]
I think, configuring this in the front matter or even the config file is a terrible idea. Just remember that there are potentially hundreds of strings that need to be translated.

However, there is already a solution out there that solves this using liquid tags and a (language-specific) translation file: https://github.com/drallgood/jekyll-multilingual/blob/master/translation_plugin.rb

It's basically a copy of this (with a few important omissions):
https://github.com/screeninteraction/jekyll-multiple-languages-plugin

**Comment by krrrcks** [comment]
Thanks. Great to hear that something for these translations already exists. Would be great to have that "out of the box".

**Comment by imathis** [comment]
Using a language dictionary is an interesting feature. Implementing it seems to be fairly complicated and I wonder how often it would just be easier to write out the site for each language manually. @drallgood Do you think that feature makes a big difference to people? Is it worth the effort to build, maintain, and support?

**Comment by drallgood** [comment]
I think so, yes. Otherwise you'd essentially need to duplicate your entire template (or at least the parts that contain text) which makes changes really difficult. Especially when we're talking about a bigger set of languages (>2).

The dictionary approach keeps your templates clean and the translations somewhat maintainable.

**Comment by krrrcks** [comment]
I would support that as well. Several German friends of me iasked "How to I get a 'German' blog?" Therefore it may be a good idea to have an easy way to switch language for the "user".

**Comment by drallgood** [comment]
Switching the language is actually pretty easy.

Here's how I do it:

``` html
<div id="language-switch">
  {% if page.lang == "de" %}
    {% assign switch_to_language =  "en" %}
    {% capture language_switch_text %}{% t global.switch %} {% t global.german %}{% endcapture %}
  {% else if page.lang == "en" %}
    {% assign switch_to_language =  "de" %}
    % capture language_switch_text %}{% t global.switch %} {% t global.english %}{% endcapture %}
  {% endif %}
  <a href="{{ site.baseurl }}/{{ switch_to_language }}/{{ page.url | remove_language }}" ><img src='{{root_url}}/images/{{ switch_to_language }}.png' alt='{{language_switch_text}}' class='flag'/></a>
</div>
```

This includes a few things not yet supported by this plugin (e.g. removing the language from an URL or translating static text)

@imathis: Have you decided whether or not not add the language dictionary thing, yet?

**Comment by imathis** [comment]
On switching language, the approach you've listed above assumes there is a translated post and that it has the same title. I know that may be the most pragmatic approach for a single site, but it would be error prone to expect this to work for all sites. It also doesn't seem to take into account that there may not be a translated post in that language.

I'm trying to decide if I want to spend time developing a system for linking posts that are translations. This way you could have an English title and a German title but you could do something like:

```
Also read in: {% translated_posts post %}  # in the post loop
```

This could generate a list of urls to other posts with all the HTML necessary (including classes so you could style them with flag images).

The thing is, I'd need a way to _link_ posts (or pages even) together. The first thing that occurred to me was to do it based on urls. So you keep some YAML file with arrays of linked posts or something, but the problem is that permalinks can be configured, so with a simple change in the _config.yml, all this becomes useless.

So, without a database, how can I link posts together in a way that won't ever break? I think my best idea is still to create a language fingerprint that translated posts can share. Perhaps I would add a command to Octopress so you can type `octopress translate _posts/[filename], _posts/[filename], _posts/[filename]`. Then it would generate a key something like `translation_id: a31asdb12t1ba` which would be uniquely based on the posts and automatically added to the YAML front-matter for each post.

Then the liquid tag would generate post lists like this:

``` ruby
def translated_posts (site)
  @translated_posts ||= site.posts.group_by { |post| post.data['translation_id'] }
end

def translate_post (post)
  links = ''
  translated_posts(post.site)[post.translation_id].reject{|p| p == post }.each do |translated_post|
    links << "<a href='#{translated_post.url}' class='post-translation lang-#{translated_post.lang}'>#{translated_post.lang}</a>"
  end
  links
end
```

I'm just roughing it out in this comment, but I think this approach would work quite well.

**Comment by drallgood** [comment]
> On switching language, the approach you've listed above assumes there is a translated post and that it has the same title.

Yeah. You're right, this approach assumes a lot (and I think I broke it when migrating to this plugin). 
Especially for cross-posts this doesn't work at all, because people will get the site in the post's language, no matter what.
It worked previously because I just duplicated cross-posts internally and used the same slug for all translations of a post. 

And I think we're lumping several issues together:
- Cross-posts and how they show up for other languages
- Linking translated posts
- Translation of static text in templates

I like the way you think in regards to linking posts together.

**Comment by imathis** [comment]
Oh, I should also say… While that would work, I'm not sure if people will use it. It's kind of a pain to have to add translation ids to every post (if you already have a blog), but I guess it's also a pain to not just use tumblr, so… maybe this is a good idea.

As far as a language dictionary goes… I'm not entirely sure how I'd approach this. Even more than linking posts, this seems like a hard feature to standardize. When I and others start shipping Octopress Ink themes and plugins, they will each have their own places where translatable words may appear. Sometimes they may be words that are written by the plugin developer, and sometimes they'll be places where the user will have to figure out how to provide configurations in two languages.

For example, in the Genesis theme (still a work in progress) you can set your site's navigation like this:

``` yaml
nav:
  - { url: '/', title: 'Posts' }
  - { url: '/archive/', title: 'Archive' }
  - { url: '/feed/', title: 'Subscribe' }
```

The plugin spins through this list and adds them to the main navigation on each page. I could support a method where users can add language keys like this:

```
nav:
  en:
    - { url: '/', title: 'Posts' }
    - { url: '/archive/', title: 'Archive' }
    - { url: '/feed/', title: 'Subscribe' }
  de:
    - { url: '/', title: 'Beiträge' }
    - { url: '/archive/', title: 'Archivieren' }
    - { url: '/feed/', title: 'Zeichnen' }
```

Note: Apologies for German, (it's Google Translate).

Now the navigation link code could use the `page.lang` to decide which array of links to spin through, but the code would have to be rewritten to accept keys or an array if the user isn't translating titles. But this isn't a standard dictionary way of handling things, this is a one-off method for each configurable thing.

I may be able to write a layer than runs between a configuration and the implementation that takes the page.lang into account so everything can work as without needing to care about language. I'm still thinking about it though.

**Comment by drallgood** [comment]
There is already a standardized way to do this (well, kind of). Most languages/frameworks (Java EE, PHP, Python, ... ) do this using dictionaries and mapping it at render time.

I don't think you necessarily need to change the configuration. 
What you'd need instead is a standardized way to define translation keys for plugins, so they don't overlap. And a way for plugins to define them, of course.

Maybe plugins can provide their own translation files, which you can overwrite if necessary (just like you can overwrite the templates of the feeds plugin)?
Maybe like this: `/plugins/<plugin name>/i18n/<lang>.yml`

This would also mean there isn't one single YAML file that contains all the translations for your site but multiple ones...

**Comment by imathis** [comment]
Well, this is something specifically for Jekyll and Liquid, so Ruby support isn't going to be that helpful. The i18n directory/language system makes sense for compiling software, but it's a pretty unfriendly user experience. I don't want single-language users to have to manage an english translation file to configure text labels, but if I don't I have an inconsistency with how German users edit English labels. I don't think many plugin developers are going to buy into supporting i18n features unless there's a way to make it hassle free for them. This approach doesn't do that for developers or for end-users.

**Comment by drallgood** [comment]
Well.. Users wouldn't have to deal with it unless they want/need to. As I said, each plugin can/should come with a set of default translations (maybe even just English. The community can always take care of the rest...).

I'm a developer with a lot of experience in creating web services that serve markets in multiple countries. So, of course, my ideas should always be taken with a grain of salt. I'm used to doing this kind of stuff... :wink:

**Comment by imathis** [comment]
I'm still noodling on this. I'm thinking about trying this (example of configuring the octopress-feeds plugin):

```
_plugins/feeds/
  config.yml
  languages/
    de.yml
    it.yml
```

Octopress ink would read in the `config.yml` as the plugin's default language's configuration, then settings from other languages would be read in as overrides for the default language. Any references to those configs, i.e. `{{ plugins.feeds.some_config }}` would be automatically read using the current languages config file, if one exists.

For this to work seamlessly, I may end up changing how this plugin works. Currently it expects you to use a `{% set_lang [lang] %}` block, during which it processes everything as under the new other language. The change I'm thinking about is adding the ability to automatically convert the language scope for any page with a `lang` setting which is not the main language. People could still use the `set_lang` Liquid tag to change language context temporarily, but it probably won't be needed very much.

**Comment by krrrcks** [comment]
That sounds good to me.

**Comment by imathis** [comment]
I just released a large change in how this plugin works. Now there's no need to use `{% set_lang %}` anymore. Post loops are automatically filtered based on each page's `lang` setting in the YAML front-matter. It works beautifully. I'm currently updating Octopress Feeds to work with this new approach, and then I'll get to work on dictionary stuff.

**Comment by drallgood** [comment]
Wow. Awesome!

I'll give it a try later and report back :smile:

**Comment by imathis** [comment]
Alright, octopress-feeds is updated, it now supports the new page.lang feature. I'm really excited for how this is coming together!

**Comment by drallgood** [comment]
Yeah. I really like it, too!

Aside from the crossposts which aren't showing up, it seems to be working :smile:

**Comment by imathis** [comment]
@drallgood, did you see that the configuration changed so that crossposts are `lang: all`?

**Comment by drallgood** [comment]
I did not. 

Is that a good solution, though? You loose the ability to identify the primary language of a post.

**Comment by imathis** [comment]
An "all" language crosspost is set to the default language, configured in `site.lang`.

**Comment by drallgood** [comment]
Yeah I got that... But what if it's written in anything but the default language?
I've got plenty of posts in either German or English, English being the default ;)

**Comment by imathis** [comment]
So you think it's a common enough scenario that people will want to crosspost from multiple source languages?

**Comment by drallgood** [comment]
That's the big question even I can't answer.
Crossposting is probably not all that common anyway, so I guess it's even less common that someone is doing it in multiple languages.

I just feel that you're loosing information if you have to set the language of a post to 'all' to crosspost it.

**Comment by imathis** [comment]
Yeah I'm not entirely sure I buy it, but I don't like having an additional config (especially one with the cumbersome name `crosspost_languages`) to add a language to all feeds. To me, `lang: all` is the simplest way to configure the likely 99% uses of an edge-case feature.

Another option would be to accept an array ['en', 'de'] and basically treat it the same way as `all` except default the language to the first item in the array instead of `site.lang`.

Or yet another option would be to leave it this way and if enough people complain. I can add a way for them to set the language and the crosspost feature at the same time.

**Comment by drallgood** [comment]
Yeah, you're absolutely right.

For me, that will mean that 99% of all posts will have to be configured with `lang: all`. Not sure whether that's helpful at all, but I guess I will have to live with it :wink:

**Comment by imathis** [comment]
Hmm. That's an interesting statistic. So in your usage, you're not as much running a multilingual blog as you are occasionally wanting to hide specific posts from one language group or another.

**Comment by drallgood** [comment]
Well.. I've got multiple sites, each one being unique in its own way:
- On my personal blog, I usually post in English (and those are all crossposts), with the occasional multilingual entry. And a few legacy posts in German (which aren't that important anyway). Static pages are fully translated.
- Another site primarily consists of German posts, with the occasional English post every now and then. Almost none of them are crossposts. 

And to be clear: I don't care whether my particular needs are met or not. I'm very aware, that I'm an edge case and will find a way to make it work either way... 

My guess would be, that there are three major use-cases for this type of plugin:
- truly multilingual sites (everything is translated)
- sites with very little overlap between the languages (i.e. there's rarely a post in one language that coincides with another in a different language). Essentially, posts are hidden from people who don't speak the language.
- sites that post only in one primary language (crossposts) but have translated the rest of the site (pages, navigation, ...)

**Comment by imathis** [comment]
Thanks for assembling these use-cases. As a monolinguist I'm not a good judge of this kind of stuff. I know over the years Octopress has been pretty popular with polylinguals and requests for a feature like this have come up often. I've avoided it until now because I hadn't figured out a simple way to get it to work. I'm still trying to figure this one out. I may change it. I'm sorry for all the runaround.

But, I just released some updates to this, Octopress Ink, and Octopress Feeds. Now all language feeds are generated automatically. So yay!

**Comment by imathis** [comment]
Alright, I've done just about everything except dictionaries. That's next. For now, if you update to 0.2.0 you'll have these new features.
- Link between posts or pages with a matching `translation_id`.
- Add translation IDs to posts or pages with `octopress translate <path>`.
- Check if a post or page has been translated with `[post or page].tranlsated`.
- Access translated posts or pages with `[post or page].tranlsations`.
- New tags `{% translations [post or page] %}` and `{% translation_list [post or page] %}` for generating links to translated posts.
- Convert language codes to language names with filter `{{ de | language_name }}`.

And in 0.1.4, I moved away from `lang: all` for crossposts and added it as `lang_crosspost: true`.

@drallgood I've update the readme and I'd love to get your feedback on these changes.

**Comment by drallgood** [comment]
Wow. That looks amazing.

I'm in the middle of implementing this on my site. `octopress translate` doesn't work yet. Neither is it showing up in `octopress -h`

Thanks for your time @imathis !!

**Comment by imathis** [comment]
@drallgood, I forgot that the CLI extension depended on a release in Octopress. I just pushed that up, and `bundle update` should let you start translating posts.

**Comment by drallgood** [comment]
Yep. That did it.
Works perfectly. Good job! :smile:

**Comment by imathis** [comment]
Alright, I've added translation dictionaries and released 0.3.0. I'd be curious to hear what you think of this. Here is how they work:

In your site's `_data` directory you can add language dictionaries with the file
naming pattern `lang_[langauge_code].yml`. For example:

```
_data
  lang_en.yml
  lang_de.yml
```

Your files might look like this:

```
# lang_en.yml
title: English title

# lang_de.yml
title: Deutsch titel
```

Now in your layouts or includes you can reference these dictionaries under the global variable `lang`. The configured page or post language will determine which language dictionary is used. For example:

```
# On a page or post where lang: en
{{ lang.title }} => English title

# On a page or post where lang: de
{{ lang.title }} => Deutsch titel
```

If no language is configured for a page or post, it will default to the site's default language.

```
# No page lang, site is configured lang: en
{{ lang.title }} =>  English title
```

Since these are Jekyll data sources, these dictionaries can also be accessed at `site.data.lang_en` and `site.data.lang_de`. This plugin merely adds the global `lang` variable and swaps out context based on configured language.

**Comment by drallgood** [comment]
Sorry it took me a while to give this a try.

Works flawlessly. Really great job!

**Comment by imathis** [comment]
Cool, so it seems like I've covered all the basic use cases of a multilingual plugin. If there's anything you run into or if I've missed something, create an issue and I'll have a look. I think I'll probably go ahead and mark this a 1.0. Thanks for all your help!
